### PR TITLE
#19: Improved logging to help troubleshoot issue where ide-versions was not reading from the file.

### LINKED ISSUE #19: Configuration file for "ide-versions" not working
**Describe the bug**
I am trying to use the "Configuration file" option for specifying the ide versions I would like to verify against. However, even after following the instructions in the README, it is giving me a generic error.

Build output:
```
Run ChrisCarini/intellij-platform-plugin-verifier-action@latest
  with:
    plugin-location: *.zip
    ide-versions: .github/workflows/ide_versions_to_verify.txt
    failure-levels: COMPATIBILITY_WARNINGS COMPATIBILITY_PROBLEMS DEPRECATED_API_USAGES INTERNAL_API_USAGES OVERRIDE_ONLY_API_USAGES NON_EXTENDABLE_API_USAGES PLUGIN_STRUCTURE_WARNINGS MISSING_DEPENDENCIES INVALID_PLUGIN NOT_DYNAMIC
  
    verifier-version: LATEST
/usr/bin/docker run --name a33c1e73c6416ae964a45a61fc7462ec98615_b9951d --label 8a33c1 --workdir /github/workspace --rm -e INPUT_PLUGIN-LOCATION -e INPUT_IDE-VERSIONS -e INPUT_FAILURE-LEVELS -e INPUT_VERIFIER-VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/intellij-autohotkey/intellij-autohotkey":"/github/workspace" 8a33c1:e73c6416ae964a45a61fc7462ec98615  "LATEST" "*.zip" ".github/workflows/ide_versions_to_verify.txt" "COMPATIBILITY_WARNINGS COMPATIBILITY_PROBLEMS DEPRECATED_API_USAGES INTERNAL_API_USAGES OVERRIDE_ONLY_API_USAGES NON_EXTENDABLE_API_USAGES PLUGIN_STRUCTURE_WARNINGS MISSING_DEPENDENCIES INVALID_PLUGIN NOT_DYNAMIC
"
Initializing...
Preparing all IDE versions specified...
Preparing [.github/workflows/ide_versions_to_verify.txt]...
  Error: =======================================================
  Error: ===-------------------------------------------------===
  Error: === An unexpected error occurred. Status code [1].
  Error: ===
  Error: === Please consider opening a bug for the developer:
  Error: ===    - Bug URL: https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/issues/new
  Error: ===    - Status Code: 1
  Error: ===-------------------------------------------------===
  Error: =======================================================
```

**To Reproduce**
This is what I have in my build_plugin.yml:
```yml
    - name: Verify Plugin Compatibility
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      with:
        plugin-location: '*.zip'
        # NOTE: For ide-versions, we just need to verify IJ community & one non-IJ IDE.
        ide-versions: .github/workflows/ide_versions_to_verify.txt
        failure-levels: >
          COMPATIBILITY_WARNINGS
          COMPATIBILITY_PROBLEMS
          DEPRECATED_API_USAGES
          INTERNAL_API_USAGES
          OVERRIDE_ONLY_API_USAGES
          NON_EXTENDABLE_API_USAGES
          PLUGIN_STRUCTURE_WARNINGS
          MISSING_DEPENDENCIES
          INVALID_PLUGIN
          NOT_DYNAMIC
```
and this is the contents of `ide_versions_to_verify.txt`:
```
ideaIC:2020.1
ideaIC:LATEST-EAP-SNAPSHOT
pycharmPC:2020.1
pycharmPC:LATEST-EAP-SNAPSHOT
```

**Expected behavior**
It should work the same as if I just listed the 4 ide versions directly in the yml file like this:
```
- name: Verify Plugin Compatibility
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      with:
        plugin-location: '*.zip'
        # NOTE: For ide-versions, we just need to verify IJ community & one non-IJ IDE.
        ide-versions |
          ideaIC:2020.1
          ideaIC:LATEST-EAP-SNAPSHOT
          pycharmPC:2020.1
          pycharmPC:LATEST-EAP-SNAPSHOT
```
(I have already tried the above configuration and it works fine, so it doesn't make sense why the text-file version doesn't work.)

**Desktop (please complete the following information):**
 - OS: The GitHub action is using whatever Dockerfile is being run by the action

**Additional context**
Build output link: https://github.com/Nordgedanken/intellij-autohotkey/pull/57/checks?check_run_id=2536385085

### PR DESCRIPTION
**Pull request by takanuva15**
Hi, I raised bug #19 because the action was not reading from the file even when I had specified it. To help debug the issue, I turned on debug logging but it still didn't give me any information why the action was failing to read the file.

After checking out and reading the source code bash script, I finally realized that I would need to checkout my repository for the script to have access to the file. (We have a custom workflow running where we just download the plugin zip file for the compatibility check, rather than checking out the entire repository).

To help future users of this action to quickly debug the issue and not raise new bugs, I have added some logging in the relevant if-condition that will notify the user about whether a file was detected for their `ide-versions` input.

image

closes #19

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -139,6 +139,9 @@ if [[ -f "$GITHUB_WORKSPACE/$INPUT_IDE_VERSIONS" ]]; then
   echo "$INPUT_IDE_VERSIONS" | while read -r INPUT_IDE_VERSION; do
     gh_debug "                   => $INPUT_IDE_VERSION"
   done
+else
```
Comment (ChrisCarini) [inline entrypoint.sh:142]: I wonder if there is some check we could have to test if the input is (intended to be) a file and only print this message then. Would it make sense to see if the `$INPUT_IDE_VERSIONS` variable either ends in `.txt` and/or does *not* contain a `:` (used to separate the IDE and version)? I am open to any other ideas.

I would prefer to not have this message printed during a 'normal' path, as it might mislead or cause confusion for people. Hence my desire for a more specific check here.

What do you think?

File: README.md [hunk 2]
```diff
@@ -153,6 +153,7 @@ file path to a file containing the IDE and versions. Below are the respective ex
 
 **Workflow File:**
 ```yaml
+- uses: actions/checkout@v2 #must checkout the repo for the action to have access to the configuration file
```
Comment (ChrisCarini) [inline README.md:156]:
```suggestion
- uses: actions/checkout@v2 # Your repository must be checked out in order to access the `ide_versions_file.txt` configuration file.

```

**Review by ChrisCarini — COMMENTED** [review]
Hi @takanuva15 - thank you for your time and effort in submitting this PR (and, for using the verifier GH action!).

One suggested change and wanted to get your thoughts on the `else` condition.

I think the general change you are proposing here (printing better messaging to the user when they try to specify an input file) is a great idea.

File: entrypoint.sh (hunk 1 above)
Comment (takanuva15) [reply entrypoint.sh]: Yep, that sounds better. I've changed the `else` to `elif` and check whether the string doesn't contain a `:` before printing the message

File: README.md (hunk 2 above)
Comment (takanuva15) [reply README.md]: done

**Review by ChrisCarini — APPROVED** [review]

**Comment by ChrisCarini** [comment]
Thank you @takanuva15 ! I will release a new version sometime in the next day or so (and, I'll try to remember to bump the `latest` tag as well ;) ). Thank you again for your contribution!

**Comment by ChrisCarini** [comment]
@takanuva15 - I just released version `v1.0.6` (and tagged it as `latest`). Thank you again for your contribution and usage of this GitHub action!

**Comment by ChrisCarini** [comment]
@all-contributors please add @takanuva15 for bug, code
